### ISSUE TITLE
MH ET LIVE ESP32

### ISSUE THREAD

**Issue by deathly1987** [geertmeersman/energie-meter#2]
Hi,

i have the water meter running with your Github:
[D1 Mini](https://www.amazon.de/dp/B01N9RXGHY?ref=ppx_yo2ov_dt_b_fed_asin_title)
[LJ18A3-8-Z/BX](https://www.amazon.de/dp/B071FTP2ZP?ref=ppx_yo2ov_dt_b_fed_asin_title)
Unfortunately, the sensor.water doesn't work.

Edit: i found the error..

The bigger problem, however, is that I would like to track the gas meter with a [MH ET LIVE ESP32MiniKit](https://www.amazon.de/dp/B0B4296Q8M?ref=ppx_yo2ov_dt_b_fed_asin_title) & reed contact, but unfortunately that doesn't work

Thanks

greeting
Andre

**Comment by geertmeersman** [comment]
Hi Andre, can you detail it a little bit more? What exactly doesn't work? And what do you have in your  logs?
